from transformers import AutoConfig
from measurement_pred.configuration_code_gen_mp import CodeGenMeasurementPredictorConfig
from measurement_pred.modeling_code_gen_mp import CodeGenMeasurementPredictor

CodeGenMeasurementPredictorConfig.register_for_auto_class()
CodeGenMeasurementPredictor.register_for_auto_class("AutoModel")
CodeGenMeasurementPredictor.register_for_auto_class("AutoModelForSequenceClassification")

code_gen_tiny_config = AutoConfig.from_pretrained("Salesforce/codegen-350M-mono")
code_gen_mp_config = CodeGenMeasurementPredictorConfig(**code_gen_tiny_config.to_dict())
code_gen_mp = CodeGenMeasurementPredictor(code_gen_mp_config)
code_gen_mp.push_to_hub("codegen-350M-mono-mp")